### ISSUE TITLE
Create a demo on Hugging Face? 

### ISSUE THREAD

**Issue by adeenayakup** [FudanDISC/DISC-MedLLM#1]
Hi!

Very cool work! It would be nice to create a demo on the [Hugging Face Hub](https://huggingface.co/spaces)!

It will help to wider reach of your work to the ecosystem.

This is a [step-by-step guide](https://huggingface.co/docs/hub/spaces-sdks-gradio) explaining the process in case you're interested.

Please let us know if you would be interested and if you have any questions. 😊

**Comment by F1mc** [comment]
Thank you so much for your kind words and for considering our work a good fit for the Hugging Face Hub. We appreciate the opportunity to reach a wider audience through your platform.

However, we've already set up our own demo environment tailored to our specific needs. Since our work is based on a large language model, the hardware constraints on Hugging Face spaces are unfortunately not a good match for our requirements. Even if it were technically feasible to run our demo on the Hub, the associated costs would likely be prohibitively high for us at this time.

We are grateful for your interest and support, and we'll certainly keep the Hugging Face Hub in mind for any future projects that might be a better fit.
